### ISSUE TITLE
25.2.0 memory leak

### ISSUE THREAD

**Issue by jonanon20** [Consensys/web3signer#1073]
We have noticed since the upgrade from 24.12.0 to 25.2.0 a significant increase in memory usage that has caused several jvm OOM errors. Our web3signers are responsible for 10s of thousands of keys and this issue appeared after onboarding a new series of ~200keys leading to the OOM crash and missed attestations.

![Image](https://github.com/user-attachments/assets/086e65e0-d94c-4ec3-b630-79836f849be1)

You can see from the graph that with version 24.12.0 we didn’t have  this memory issue, as soon as we deployed 25.2.0 on 19/02 then memory usage spiked considerably. As a temporary measure we have set our  `-XX:MaxRAMPercentage=50` and given our nodes more memory, we generally see memory usage plateau but the plateau will only last a day or 2 before it climbs again. This gradual climb continues until we are alerted and have to restart. Originally we were at `-XX:MaxRAMPercentage=25` without any issues or memory spikes. Memory usage for the web3signer up until 25.2.0 has always been consistently low.

When we onboarded 200 new keys and we had missed attestations we noticed a considerable jvm garbage collection time as shown on the graph below across 2 of our 3 signers (jvm_gc_collection_seconds).  
![Image](https://github.com/user-attachments/assets/5883cc44-f90a-46ba-822f-579aabfec67e)

despite the long gc times we didnt see any reduction in memory for 2 of our signers during this period but this could be the result of memory pressure at the time.

We have noticed a worrying increase in memory and a gradual climb over several days. Where before 25.2.0 we were seeing a usage of ~1GB with no issues we now gradually climb beyond 6GB after 2 or 3 days.

**Comment by usmansaleem** [comment]
@jonanon20 do you use the `/reload` API call or restart web3signer instances to onboard new keys?

**Comment by jonanon20** [comment]
Yes that right, we use the /reload API

**Comment by usmansaleem** [comment]
@jonanon20 Can you provide some more details for us to debug, such as:
- How Web3Signer is deployed, via docker image or via binary
- How the keys are loaded, using keystore files or via AWS/Azure?
- What is the total memory allocated to Web3Signer instance? Also, system memory/CPU.

Thanks/ Uzi

**Comment by jonanon20** [comment]
Hello, we deploy to kubernetes using the docker image `consensys/web3signer:25.2.0`. We have a sidecar that writes the keys  to disk before hitting the `/reload` endpoint. We set the env var `WEB3SIGNER_KEY_STORE_PATH`.

We are running the pod on an m5.2xlarge AWS instance. 8vCPU and 32GiB.
The web3signer container has the following resource requests:
```
resources:
  limits:
    memory: 12Gi
  requests:
    cpu: "4"
    memory: 9Gi
```
There is a pod anti affinity so multiple web3signers cannot be loaded onto the same node. There is no memory pressure on the node itself, only the pod after a couple of days. We still get jvm oom errors even after trippling our requests/limits, it just takes a few more days to fail.

We launch the container with the arg `eth2` and we use the following `WEB3SIGNER_OPTS`:
```
- name: WEB3SIGNER_OPTS
  value: -Djava.util.concurrent.ForkJoinPool.common.parallelism=4 -XX:+DisableAttachMechanism -XX:-HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/dev/null -XX:MaxRAMPercentage=50.0
```

**Comment by usmansaleem** [comment]
@jonanon20 If possible, can you DM me on Discord (`usmans.info`) or on Consensys discord server Web3Signer channel (https://discord.gg/consensys) or on Telegram (`@usmans_info`). There are few questions about keystore parameters that I would like to ask directly. In addition, this will allow me to hook us up with our performance engineers as well. BR, Uzi.

**Comment by jtfigment** [comment]
Hi @usmansaleem, I have left a few messages on discord, I wonder if you have had a chance to look at them? We have still been getting oom issues.

**Comment by jonanon20** [comment]
Hi @usmansaleem , I have sent a couple of messages to you over discord, I wonder if you have had the chance to see them?  We're still getting oom issues with this.

**Comment by aimxhaisse** [comment]
We also see a similar leak with `/reload`, I've shared details to Uzi on Disccord.

**Comment by ahamlat** [comment]
Hi @jonanon20,
Could you generate a heap dump, load it with Eclipse memory analyzer tool (https://eclipse.dev/mat/download/), and share the histogram view like below. 

<img width="835" alt="Image" src="https://github.com/user-attachments/assets/9270d1bd-c2af-45ea-bdd8-a52e79149cbf" />

**Comment by ahamlat** [comment]
Any update on this issue ?

**Comment by usmansaleem** [comment]
@jonanon20 @aimxhaisse Can you try updating to latest W3S release and see if you still seeing OOM/increase memory issues: https://github.com/Consensys/web3signer/releases/tag/25.6.0 . We may still need a heapdump screenshot as mentioned by Ameziane above to analyse further if you still face memory issue.

**Comment by echo-dev-99** [comment]
@usmansaleem, apologies for the delayed response here. Following up on jonanon20's report - I've been picking up the investigation and monitoring our reload patterns over the last couple of weeks since we deployed `25.6.0`.

It's sad to say that we do indeed continue to hit this memory leak issue.

I don't know if this bit of information will help, I am seeing that after the initial key loading which can take a few minutes, each subsequent reload appears to take around ~1 second.

<img width="511" height="443" alt="Image" src="https://github.com/user-attachments/assets/eea26169-4b32-43d5-b3ff-75a4aec9c4d2" />

We regularly see log messages like, which I presume is the `/reload` process kicking in.
```
Loading and converting SigningMetadata to ArtifactSigner using parallel streams
Total Paths cached: N, Error count: 0
```
_OR_
In cases where keys are removed, we see the total paths cached value change by `N`:
```
Removed N cached metadata files that has not been loaded.
Total Paths cached: Y, Error count: 0
```

So whilst the cache numbers fluctuate up _and_ down as I would expect, memory usage only grows from pod startup until we have to intervene, or the pod is OOMkilled, which can take anywhere up to roughly a working week.

To me this suggests that despite cache cleanup appearing to work, cached objects aren't being properly garbage collected, causing cumulative memory growth.

**Comment by echo-dev-99** [comment]
Hi @usmansaleem, just following up on this issue as we're still experiencing these memory problems in production.
I came across your documentation mentioning:

> Web3Signer consumes less than 2 GB of JVM heap while managing 10,000 keys in this setup.
> The test configuration connects one validator client to Web3Signer. Using multiple validator clients might change resource requirements.

Since we're managing significantly more keys than the documented 10k example (as jonanon20 alluded to), and using multiple validator clients, it would be really helpful to understand:

- What's the expected memory scaling pattern as key count increases - is it roughly linear or are there other factors?
- How much does each additional validator client connection impact memory usage?
- Are there recommended JVM heap configurations for larger deployments?
- Has there been a change in memory requirements per key between `24.12.0` and `25.x.x`?

As mentioned in our original report, we've had to increase our `-XX:MaxRAMPercentage` from `25` to `50` and add more memory to our nodes as a temporary measure, but we're still seeing the gradual memory climb that requires periodic restarts.
Understanding the expected memory requirements for larger-scale deployments would help us determine if this is purely a memory leak issue or if we also need to adjust our baseline capacity planning.

Any guidance would be appreciated!

**Note**: I did find this blog from a couple of years ago where it looks like Kiln worked with you to run w3s at scale, were there any learnings from that could help here? https://www.kiln.fi/post/learnings-from-running-web3signer-at-scale-on-holesky

**Comment by aimxhaisse** [comment]
I wrote this article :)

We are still seeing this issue & I've shared some details on discord about our usage. Right now our temporary fix is to restart from time to time our instances, which is not the most ideal situation but works.

We can reproduce the issue both in testnet (hoodi, holesky) and mainnet with setups of like 30, 60K keys and up to 120K keys on Holesky. I don't think there should be a limit on the number of keys here, ultimately the scaling side is on the database and web3signer should be able to horizontally scale without limits.

The long-term fix is not to throw more resources at it though it can help delaying the moment it will start crashing, there is an issue that needs to be fixed on the code.

**Comment by usmansaleem** [comment]
@echo-dev-99 I am revisiting the keys loading logic and running debugger to identify the memory leak.

**Comment by usmansaleem** [comment]
@aimxhaisse @echo-dev-99 Please give https://github.com/Consensys/web3signer/releases/tag/25.12.0 a go and let us know if there is still memory leak being observed.

**Comment by echo-dev-99** [comment]
Hey @usmansaleem. Sorry for the long delay in getting back to you. Been busy with a few other things.

We are still seeing monotonic Old Gen growth on `25.12.0` under high validator load. In our highest-load cluster, after suspending scheduled restarts, Old Gen grew monotonically for 10 days at **~230 MB/day**, reaching **~2.3 GB** (as of writing). Lower-load clusters remained flat, so the effect appears to scale with key count.

From static review, the clearest retention candidate in the reload path is `RegisteredValidators`. On each reload, `DefaultArtifactSignerProvider.load()` passes the full signer key set to `PostLoadingValidatorsProcessor`, which registers those keys into `RegisteredValidators`. `RegisteredValidators` stores them in a process-lifetime `HashBiMap` and never removes stale entries. If validator membership churns across reloads, stale entries will remain strongly reachable indefinitely. We are not claiming this map alone explains the full weekly heap increase, only that it is one clear monotonic structure in the reload path and a strong candidate to investigate first.

We also checked `26.3.0`: commit `849e3c3` adds synchronization to `RegisteredValidators`, but there still does not appear to be any stale-entry removal.

We have not confirmed this with heap dumps. We prefer to avoid collecting dumps from signing pods, and our pods are configured with `-XX:+DisableAttachMechanism`, `-XX:-HeapDumpOnOutOfMemoryError`, and `-XX:HeapDumpPath=/dev/null`

Could you take a look at whether `RegisteredValidators` is expected to be monotonic across reloads, or whether stale validator entries should be removed?

**Comment by usmansaleem** [comment]
@echo-dev-99 Release 26.4.1 has fixed two memory contention issues identified in RegisteredValidators and ValidatorDao. Thanks for pointing in right direction.

**Comment by echo-dev-99** [comment]
@usmansaleem Great news. we've deployed and will monitor over the next few days and hopefully feedback with some good news 🤞

**Comment by echo-dev-99** [comment]
@usmansaleem looking great so far! see the before and after 😄 (after we deployed in our environment with a large numOf keys

<img width="863" height="335" alt="Image" src="https://github.com/user-attachments/assets/b349e5ac-f352-486a-b5f8-d188abcb651c" />
